<div class="social-feedback-container">
	<div class="save-container">
		<input name="l7lc-settings" id="js-feedback-button" class="button button-primary" type="submit" value="<?php _e( 'Save Changes', 'l7-login-customizer' ); ?>" />
		<a name="<?php _e( 'Preview of custom login. Saved changes are shown here.', 'l7-login-customizer' ) ?>" href="#TB_inline?width=700&height=700&inlineId=jsm_custom_login_display" class="thickbox"><button class="button button-secondary"><?php _e( 'Preview' , 'l7-login-customizer' ); ?></button></a>
	</div>
	<div class="feedback-container">
		<h4>LEAVE FEEDBACK</h4>
		<div class="input-group">
			<div id="js-review" class="feedback-circle"></div>
			<div class="feedback-label">I would like to review this plugin.</div>
		</div>
		<div class="input-group">
			<div id="js-improve" class="feedback-circle"></div>
			<div class="feedback-label">I have ideas to improve this plugin.</div>
		</div>
		<div class="input-group">
			<div id="js-help" class="feedback-circle"></div>
			<div class="feedback-label">I need help with this plugin.</div>
		</div>
	</div>
	<div class="facebook-container">
		<form name="paypal" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
			<input type="hidden" name="cmd" value="_s-xclick">
			<input type="hidden" name="hosted_button_id" value="Z5AWARCR4PRM4">
			<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
			<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
		</form>
		<p>Keeping this plugin up to date requires a lot of coffee. All coffee donations are greatly appreciated.</p>
	</div>
</div> 